server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-serie
spring:
  application:
    name: api-serie
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

urlCheck: http://localhost:8080

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/